language: generic
sudo: false
script: boot-driver test
branches:
  only:
    - master
    - releng
before_cache:
  - rm -rf $HOME/.boot/cache/tmp/
cache:
  directories:
    - $HOME/.m2
    - $HOME/.boot
matrix:
  include:
    - env: JDK=zulu7
    - env: JDK=zulu8
    - env: JDK=zulu8 CLOJURE=1.8
    - env: JDK=zulu9
  allow_failures:
    - env: JDK=zulu9

before_install:
  - curl -fsSLo init.sh http://irresponsible.github.io/tools.travis.jdk-installer/init.sh
  - source init.sh
  - jdk-installer install "${JDK}"
  - boot-driver install-boot
  - boot-driver setup-env
  - java -version
install:
  - boot-driver install-deps
